### ISSUE TITLE
Blocks have gaps in them when player is moved

### ISSUE THREAD

**Issue by fesdonomist** [PlebusSupremus1234/Cubeys-Adventure#2]
When I move the player, the blocks have gaps in them that flash around when I continue to move the player, then they slowly fade away as I stop moving the player.
![image](https://user-images.githubusercontent.com/71878148/124067001-f4a22900-da7c-11eb-9ce1-8ed1081f8f8a.png)

**Comment by PlebusSupremus1234** [comment]
Fixed, sorta
