### ISSUE TITLE
:peepopain:

### ISSUE THREAD

**Issue by fesdonomist** [PlebusSupremus1234/Cubeys-Adventure#5]
Uploading 2021-07-02 17-56-01.mp4…

:Douleurpeepo:

**Comment by fesdonomist** [comment]
bruh 

https://user-images.githubusercontent.com/71878148/124241664-4a4f0200-db5f-11eb-84ed-05c3dba26cbe.mp4

**Comment by PlebusSupremus1234** [comment]
Fixed with 1 line ;-;
